2025-04-06 01:16:03,651 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'init' at Sun, 06 Apr 2025 01:16:03 +0000. Up 8.27 seconds.
2025-04-06 01:16:03,651 - main.py[DEBUG]: No kernel command line url found.
2025-04-06 01:16:03,651 - main.py[DEBUG]: Closing stdin.
2025-04-06 01:16:03,652 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=False)
2025-04-06 01:16:03,670 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-04-06 01:16:03,677 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=False)
2025-04-06 01:16:03,678 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2025-04-06 01:16:03,683 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-instance (recursive=False)
2025-04-06 01:16:03,684 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2025-04-06 01:16:03,700 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-once (recursive=False)
2025-04-06 01:16:03,702 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2025-04-06 01:16:03,720 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-boot (recursive=False)
2025-04-06 01:16:03,722 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2025-04-06 01:16:03,742 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/vendor (recursive=False)
2025-04-06 01:16:03,743 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-04-06 01:16:03,770 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/seed (recursive=False)
2025-04-06 01:16:03,770 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-04-06 01:16:03,800 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances (recursive=False)
2025-04-06 01:16:03,801 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-04-06 01:16:03,840 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/handlers (recursive=False)
2025-04-06 01:16:03,841 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-04-06 01:16:03,864 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/sem (recursive=False)
2025-04-06 01:16:03,866 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data (recursive=False)
2025-04-06 01:16:03,866 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init (recursive=True)
2025-04-06 01:16:03,869 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/sem (recursive=False)
2025-04-06 01:16:03,880 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2025-04-06 01:16:03,882 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2025-04-06 01:16:03,883 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2025-04-06 01:16:03,884 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 0:4
2025-04-06 01:16:03,884 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 3 bytes
2025-04-06 01:16:03,886 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2025-04-06 01:16:03,887 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2025-04-06 01:16:03,888 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2025-04-06 01:16:03,901 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2025-04-06 01:16:03,909 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2025-04-06 01:16:03,921 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2025-04-06 01:16:03,922 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2025-04-06 01:16:03,922 - stages.py[DEBUG]: no cache found
2025-04-06 01:16:03,922 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
2025-04-06 01:16:03,922 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2025-04-06 01:16:03,968 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-04-06 01:16:03,969 - __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
2025-04-06 01:16:03,985 - __init__.py[DEBUG]: Searching for network data source in: ['DataSourceEc2', 'DataSourceNone']
2025-04-06 01:16:03,985 - handlers.py[DEBUG]: start: init-network/search-Ec2: searching for network data from DataSourceEc2
2025-04-06 01:16:03,985 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
2025-04-06 01:16:03,985 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2025-04-06 01:16:03,985 - util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
2025-04-06 01:16:03,985 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_uuid
2025-04-06 01:16:03,985 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2025-04-06 01:16:03,986 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2025-04-06 01:16:03,986 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
2025-04-06 01:16:03,986 - DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_name=aws cloud_platform=ec2
2025-04-06 01:16:03,986 - util.py[DEBUG]: Skipping DNS checks of IP address 169.254.169.254
2025-04-06 01:16:03,986 - util.py[DEBUG]: Resolving URL: http://169.254.169.254:80 took 0.000 seconds
2025-04-06 01:16:03,986 - util.py[DEBUG]: Skipping DNS checks of IP address fd00:ec2::254
2025-04-06 01:16:03,986 - util.py[DEBUG]: Resolving URL: http://[fd00:ec2::254]:80 took 0.000 seconds
2025-04-06 01:16:03,986 - DataSourceEc2.py[DEBUG]: Fetching Ec2 IMDSv2 API Token
2025-04-06 01:16:03,987 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/latest/api/token' with {'url': 'http://169.254.169.254:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'timeout': 50.0, 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2025-04-06 01:16:04,001 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/latest/api/token (200, 56b) after 1 attempts
2025-04-06 01:16:04,002 - DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254:80'
2025-04-06 01:16:04,002 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,010 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2025-04-06 01:16:04,010 - DataSourceEc2.py[DEBUG]: Found preferred metadata version 2021-03-23
2025-04-06 01:16:04,010 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/user-data' with {'url': 'http://169.254.169.254:80/2021-03-23/user-data', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,013 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/user-data (200, 2448b) after 1 attempts
2025-04-06 01:16:04,014 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,020 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ (200, 305b) after 1 attempts
2025-04-06 01:16:04,021 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,030 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
2025-04-06 01:16:04,031 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,040 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami (200, 4b) after 1 attempts
2025-04-06 01:16:04,041 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,050 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
2025-04-06 01:16:04,051 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,060 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/ (200, 12b) after 1 attempts
2025-04-06 01:16:04,062 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,070 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/ (200, 17b) after 1 attempts
2025-04-06 01:16:04,072 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,080 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history (200, 2b) after 1 attempts
2025-04-06 01:16:04,081 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,090 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled (200, 2b) after 1 attempts
2025-04-06 01:16:04,091 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,100 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/ (200, 26b) after 1 attempts
2025-04-06 01:16:04,101 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,104 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/info (200, 205b) after 1 attempts
2025-04-06 01:16:04,105 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,107 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ (200, 4b) after 1 attempts
2025-04-06 01:16:04,107 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,120 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/ (200, 26b) after 1 attempts
2025-04-06 01:16:04,121 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,124 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info (200, 98b) after 1 attempts
2025-04-06 01:16:04,125 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,127 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/ (200, 7b) after 1 attempts
2025-04-06 01:16:04,127 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,130 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
2025-04-06 01:16:04,130 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,133 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/ (200, 11b) after 1 attempts
2025-04-06 01:16:04,133 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,135 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/ (200, 5b) after 1 attempts
2025-04-06 01:16:04,135 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,144 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
2025-04-06 01:16:04,144 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,148 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/ (200, 230b) after 1 attempts
2025-04-06 01:16:04,148 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/ipv4-associations/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/ipv4-associations/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,151 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/ipv4-associations/ (200, 14b) after 1 attempts
2025-04-06 01:16:04,151 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/ipv4-associations/34.203.223.152' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/ipv4-associations/34.203.223.152', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,160 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/ipv4-associations/34.203.223.152 (200, 13b) after 1 attempts
2025-04-06 01:16:04,161 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/device-number' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/device-number', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,164 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/device-number (200, 1b) after 1 attempts
2025-04-06 01:16:04,165 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/interface-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/interface-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,167 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/interface-id (200, 21b) after 1 attempts
2025-04-06 01:16:04,167 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,169 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/local-hostname (200, 29b) after 1 attempts
2025-04-06 01:16:04,170 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/local-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/local-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,180 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/local-ipv4s (200, 13b) after 1 attempts
2025-04-06 01:16:04,181 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,183 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/mac (200, 17b) after 1 attempts
2025-04-06 01:16:04,183 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/owner-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/owner-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,188 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/owner-id (200, 12b) after 1 attempts
2025-04-06 01:16:04,188 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,190 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/public-hostname (200, 42b) after 1 attempts
2025-04-06 01:16:04,190 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/public-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/public-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,192 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/public-ipv4s (200, 14b) after 1 attempts
2025-04-06 01:16:04,192 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/security-group-ids' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/security-group-ids', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,200 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/security-group-ids (200, 20b) after 1 attempts
2025-04-06 01:16:04,200 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,203 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/security-groups (200, 56b) after 1 attempts
2025-04-06 01:16:04,203 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/subnet-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/subnet-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,205 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/subnet-id (200, 24b) after 1 attempts
2025-04-06 01:16:04,205 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/subnet-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,210 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/subnet-ipv4-cidr-block (200, 14b) after 1 attempts
2025-04-06 01:16:04,210 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/vpc-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/vpc-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,212 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/vpc-id (200, 21b) after 1 attempts
2025-04-06 01:16:04,213 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/vpc-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,215 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/vpc-ipv4-cidr-block (200, 13b) after 1 attempts
2025-04-06 01:16:04,215 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/vpc-ipv4-cidr-blocks', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,217 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:ff:c3:02:fb:cf/vpc-ipv4-cidr-blocks (200, 13b) after 1 attempts
2025-04-06 01:16:04,217 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,220 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/ (200, 45b) after 1 attempts
2025-04-06 01:16:04,220 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,222 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone (200, 10b) after 1 attempts
2025-04-06 01:16:04,223 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,225 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id (200, 8b) after 1 attempts
2025-04-06 01:16:04,225 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,227 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/region (200, 9b) after 1 attempts
2025-04-06 01:16:04,227 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,241 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/ (200, 16b) after 1 attempts
2025-04-06 01:16:04,242 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,245 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/domain (200, 13b) after 1 attempts
2025-04-06 01:16:04,246 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,249 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/partition (200, 3b) after 1 attempts
2025-04-06 01:16:04,249 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,260 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-id (200, 21b) after 1 attempts
2025-04-06 01:16:04,261 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,263 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index (200, 1b) after 1 attempts
2025-04-06 01:16:04,263 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,266 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path (200, 9b) after 1 attempts
2025-04-06 01:16:04,266 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,280 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/hostname (200, 29b) after 1 attempts
2025-04-06 01:16:04,281 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,289 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-action (200, 4b) after 1 attempts
2025-04-06 01:16:04,289 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,292 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2025-04-06 01:16:04,292 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,300 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle (200, 9b) after 1 attempts
2025-04-06 01:16:04,300 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,303 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-type (200, 8b) after 1 attempts
2025-04-06 01:16:04,303 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,306 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-hostname (200, 29b) after 1 attempts
2025-04-06 01:16:04,306 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,309 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4 (200, 13b) after 1 attempts
2025-04-06 01:16:04,309 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,321 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/mac (200, 17b) after 1 attempts
2025-04-06 01:16:04,322 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/profile' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/profile', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,324 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/profile (200, 11b) after 1 attempts
2025-04-06 01:16:04,325 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,327 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-hostname (200, 42b) after 1 attempts
2025-04-06 01:16:04,327 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,340 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4 (200, 14b) after 1 attempts
2025-04-06 01:16:04,341 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,343 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/reservation-id (200, 19b) after 1 attempts
2025-04-06 01:16:04,343 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,346 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/security-groups (200, 56b) after 1 attempts
2025-04-06 01:16:04,346 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,350 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity (200, 32b) after 1 attempts
2025-04-06 01:16:04,350 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,353 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document (200, 477b) after 1 attempts
2025-04-06 01:16:04,353 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,355 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7 (200, 1175b) after 1 attempts
2025-04-06 01:16:04,355 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,360 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048 (200, 1491b) after 1 attempts
2025-04-06 01:16:04,361 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-04-06 01:16:04,363 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature (200, 174b) after 1 attempts
2025-04-06 01:16:04,363 - util.py[DEBUG]: Crawl of metadata service took 0.377 seconds
2025-04-06 01:16:04,367 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-aws - wb: [644] 4 bytes
2025-04-06 01:16:04,367 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2025-04-06 01:16:04,368 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2025-04-06 01:16:04,369 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-aws'
2025-04-06 01:16:04,370 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmpg7ja4lvq) - w: [600] 11962 bytes/chars
2025-04-06 01:16:04,371 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmpkphsv_bt) - w: [644] 7820 bytes/chars
2025-04-06 01:16:04,371 - handlers.py[DEBUG]: finish: init-network/search-Ec2: SUCCESS: found network data from DataSourceEc2
2025-04-06 01:16:04,371 - stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
2025-04-06 01:16:04,372 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-04-06 01:16:04,372 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2025-04-06 01:16:04,372 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2025-04-06 01:16:04,409 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2025-04-06 01:16:04,410 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2025-04-06 01:16:04,410 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2025-04-06 01:16:04,411 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2025-04-06 01:16:04,411 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2025-04-06 01:16:04,411 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2025-04-06 01:16:04,414 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-04-06 01:16:04,414 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-04-06 01:16:04,414 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2025-04-06 01:16:04,420 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2025-04-06 01:16:04,420 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2025-04-06 01:16:04,420 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2025-04-06 01:16:04,422 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-04-06 01:16:04,422 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-04-06 01:16:04,422 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-04-06 01:16:04,423 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2025-04-06 01:16:04,423 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-0278353425af7a49b'
2025-04-06 01:16:04,430 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b (recursive=True)
2025-04-06 01:16:04,435 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/handlers (recursive=False)
2025-04-06 01:16:04,436 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b (recursive=True)
2025-04-06 01:16:04,453 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/scripts (recursive=False)
2025-04-06 01:16:04,454 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b (recursive=True)
2025-04-06 01:16:04,463 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem (recursive=False)
2025-04-06 01:16:04,464 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-0278353425af7a49b/datasource (quiet=False)
2025-04-06 01:16:04,464 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/datasource - wb: [644] 29 bytes
2025-04-06 01:16:04,465 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/datasource (recursive=False)
2025-04-06 01:16:04,467 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/datasource (recursive=False)
2025-04-06 01:16:04,467 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
2025-04-06 01:16:04,468 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2025-04-06 01:16:04,469 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2025-04-06 01:16:04,479 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2025-04-06 01:16:04,480 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2025-04-06 01:16:04,480 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2025-04-06 01:16:04,480 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2025-04-06 01:16:04,482 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2025-04-06 01:16:04,482 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2025-04-06 01:16:04,483 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2025-04-06 01:16:04,483 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2025-04-06 01:16:04,484 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2025-04-06 01:16:04,484 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2025-04-06 01:16:04,485 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2025-04-06 01:16:04,488 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 12529 bytes
2025-04-06 01:16:04,488 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/obj.pkl (recursive=False)
2025-04-06 01:16:04,489 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/obj.pkl (recursive=False)
2025-04-06 01:16:04,490 - main.py[DEBUG]: [net] init will now be targeting instance id: i-0278353425af7a49b. new=True
2025-04-06 01:16:04,490 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-04-06 01:16:04,490 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2025-04-06 01:16:04,490 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2025-04-06 01:16:04,514 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2025-04-06 01:16:04,514 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2025-04-06 01:16:04,514 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2025-04-06 01:16:04,516 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2025-04-06 01:16:04,516 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2025-04-06 01:16:04,516 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2025-04-06 01:16:04,519 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-04-06 01:16:04,519 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-04-06 01:16:04,519 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2025-04-06 01:16:04,524 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2025-04-06 01:16:04,524 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2025-04-06 01:16:04,524 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2025-04-06 01:16:04,527 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-04-06 01:16:04,527 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-04-06 01:16:04,527 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-04-06 01:16:04,528 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-04-06 01:16:04,528 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2025-04-06 01:16:04,529 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-04-06 01:16:04,529 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2025-04-06 01:16:04,539 - util.py[DEBUG]: Reading from /sys/class/net/ens5/name_assign_type (quiet=False)
2025-04-06 01:16:04,539 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/name_assign_type
2025-04-06 01:16:04,540 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-04-06 01:16:04,540 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2025-04-06 01:16:04,540 - util.py[DEBUG]: Reading from /sys/class/net/ens5/carrier (quiet=False)
2025-04-06 01:16:04,540 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/carrier
2025-04-06 01:16:04,540 - util.py[DEBUG]: Reading from /sys/class/net/ens5/addr_assign_type (quiet=False)
2025-04-06 01:16:04,540 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/addr_assign_type
2025-04-06 01:16:04,540 - util.py[DEBUG]: Reading from /sys/class/net/ens5/uevent (quiet=False)
2025-04-06 01:16:04,540 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/ens5/uevent
2025-04-06 01:16:04,540 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-04-06 01:16:04,540 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2025-04-06 01:16:04,540 - __init__.py[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2025-04-06 01:16:04,541 - util.py[DEBUG]: Reading from /sys/class/net/ens5/device/device (quiet=False)
2025-04-06 01:16:04,541 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens5/device/device
2025-04-06 01:16:04,541 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2025-04-06 01:16:04,541 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2025-04-06 01:16:04,541 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2025-04-06 01:16:04,541 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2025-04-06 01:16:04,541 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-04-06 01:16:04,541 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2025-04-06 01:16:04,541 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-04-06 01:16:04,541 - util.py[DEBUG]: Reading from /sys/class/net/ens5/type (quiet=False)
2025-04-06 01:16:04,541 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/type
2025-04-06 01:16:04,541 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2025-04-06 01:16:04,542 - util.py[DEBUG]: Read 4 bytes from /sys/class/net/lo/type
2025-04-06 01:16:04,542 - stages.py[DEBUG]: network config disabled by system_cfg
2025-04-06 01:16:04,542 - stages.py[INFO]: network config is disabled by system_cfg
2025-04-06 01:16:04,542 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2025-04-06 01:16:04,542 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2025-04-06 01:16:04,542 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/user-data.txt - wb: [600] 2448 bytes
2025-04-06 01:16:04,543 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/user-data.txt (recursive=False)
2025-04-06 01:16:04,544 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/user-data.txt (recursive=False)
2025-04-06 01:16:04,546 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2025-04-06 01:16:04,551 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/user-data.txt.i - wb: [600] 2470 bytes
2025-04-06 01:16:04,552 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/user-data.txt.i (recursive=False)
2025-04-06 01:16:04,553 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/user-data.txt.i (recursive=False)
2025-04-06 01:16:04,554 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/vendor-data.txt - wb: [600] 0 bytes
2025-04-06 01:16:04,554 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/vendor-data.txt (recursive=False)
2025-04-06 01:16:04,555 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/vendor-data.txt (recursive=False)
2025-04-06 01:16:04,557 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/vendor-data.txt.i - wb: [600] 308 bytes
2025-04-06 01:16:04,558 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/vendor-data.txt.i (recursive=False)
2025-04-06 01:16:04,570 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/vendor-data.txt.i (recursive=False)
2025-04-06 01:16:04,571 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/vendor-data2.txt - wb: [600] 0 bytes
2025-04-06 01:16:04,571 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/vendor-data2.txt (recursive=False)
2025-04-06 01:16:04,573 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/vendor-data2.txt (recursive=False)
2025-04-06 01:16:04,574 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/vendor-data2.txt.i - wb: [600] 308 bytes
2025-04-06 01:16:04,576 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/vendor-data2.txt.i (recursive=False)
2025-04-06 01:16:04,577 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/vendor-data2.txt.i (recursive=False)
2025-04-06 01:16:04,578 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-04-06 01:16:04,579 - cc_set_hostname.py[DEBUG]: Setting the hostname to ip-172-31-27-108.ec2.internal (ip-172-31-27-108)
2025-04-06 01:16:04,579 - subp.py[DEBUG]: Running command ['hostnamectl', 'set-hostname', 'ip-172-31-27-108.ec2.internal'] with allowed return codes [0] (shell=False, capture=True)
2025-04-06 01:16:04,809 - __init__.py[DEBUG]: Non-persistently setting the system hostname to ip-172-31-27-108.ec2.internal
2025-04-06 01:16:04,810 - subp.py[DEBUG]: Running command ['hostname', 'ip-172-31-27-108.ec2.internal'] with allowed return codes [0] (shell=False, capture=True)
2025-04-06 01:16:04,816 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/set-hostname (via temporary file /var/lib/cloud/data/tmpsakhhin5) - w: [644] 78 bytes/chars
2025-04-06 01:16:04,817 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/sem/consume_data - wb: [644] 25 bytes
2025-04-06 01:16:04,818 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/consume_data (recursive=False)
2025-04-06 01:16:04,829 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/consume_data (recursive=False)
2025-04-06 01:16:04,832 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-0278353425af7a49b/sem/consume_data'>)
2025-04-06 01:16:04,832 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2025-04-06 01:16:04,832 - launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
2025-04-06 01:16:04,833 - stages.py[DEBUG]: Added default handler for {'text/cloud-config', 'text/cloud-config-jsonp'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2025-04-06 01:16:04,834 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2025-04-06 01:16:04,834 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-boot'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']]
2025-04-06 01:16:04,834 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-instance'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']]
2025-04-06 01:16:04,834 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-once'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']]
2025-04-06 01:16:04,834 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2025-04-06 01:16:04,834 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]
2025-04-06 01:16:04,834 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2025-04-06 01:16:04,834 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2025-04-06 01:16:04,834 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__begin__, None, 2) with frequency once-per-instance
2025-04-06 01:16:04,834 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__begin__, None, 2) with frequency once-per-instance
2025-04-06 01:16:04,834 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__begin__, None, 2) with frequency once-per-instance
2025-04-06 01:16:04,834 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2025-04-06 01:16:04,834 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
2025-04-06 01:16:04,835 - __init__.py[DEBUG]: {'Content-Type': 'text/cloud-config; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="cloud-config.txt"'}
2025-04-06 01:16:04,835 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (text/cloud-config, cloud-config.txt, 3) with frequency once-per-instance
2025-04-06 01:16:04,835 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2025-04-06 01:16:04,836 - cloud_config.py[DEBUG]: Merging by applying [('dict', ['replace']), ('list', []), ('str', [])]
2025-04-06 01:16:04,837 - __init__.py[DEBUG]: {'Content-Type': 'text/x-shellscript; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="user-data.txt"'}
2025-04-06 01:16:04,837 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (text/x-shellscript, user-data.txt, 2) with frequency once-per-instance
2025-04-06 01:16:04,837 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/scripts/user-data.txt - wb: [700] 1799 bytes
2025-04-06 01:16:04,838 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/scripts/user-data.txt (recursive=False)
2025-04-06 01:16:04,839 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/scripts/user-data.txt (recursive=False)
2025-04-06 01:16:04,840 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2025-04-06 01:16:04,841 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/cloud-config.txt - wb: [600] 154 bytes
2025-04-06 01:16:04,842 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/cloud-config.txt (recursive=False)
2025-04-06 01:16:04,843 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/cloud-config.txt (recursive=False)
2025-04-06 01:16:04,844 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2025-04-06 01:16:04,844 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__end__, None, 2) with frequency once-per-instance
2025-04-06 01:16:04,844 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__end__, None, 2) with frequency once-per-instance
2025-04-06 01:16:04,844 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__end__, None, 2) with frequency once-per-instance
2025-04-06 01:16:04,844 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2025-04-06 01:16:04,844 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
2025-04-06 01:16:04,844 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2025-04-06 01:16:04,844 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2025-04-06 01:16:04,844 - stages.py[DEBUG]: no vendordata from datasource
2025-04-06 01:16:04,844 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2025-04-06 01:16:04,845 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2
2025-04-06 01:16:04,845 - stages.py[DEBUG]: no vendordata2 from datasource
2025-04-06 01:16:04,845 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2
2025-04-06 01:16:04,845 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-04-06 01:16:04,845 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2025-04-06 01:16:04,845 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2025-04-06 01:16:04,858 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2025-04-06 01:16:04,858 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2025-04-06 01:16:04,858 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2025-04-06 01:16:04,870 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2025-04-06 01:16:04,871 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2025-04-06 01:16:04,871 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2025-04-06 01:16:04,873 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-04-06 01:16:04,873 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-04-06 01:16:04,873 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2025-04-06 01:16:04,879 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2025-04-06 01:16:04,879 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2025-04-06 01:16:04,889 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2025-04-06 01:16:04,892 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-04-06 01:16:04,892 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-04-06 01:16:04,892 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-04-06 01:16:04,893 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-04-06 01:16:04,893 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-04-06 01:16:04,893 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2025-04-06 01:16:04,895 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:04,895 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:05,007 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-04-06 01:16:05,008 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-04-06 01:16:05,008 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2025-04-06 01:16:05,013 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2025-04-06 01:16:05,014 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 16676 bytes
2025-04-06 01:16:05,030 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/obj.pkl (recursive=False)
2025-04-06 01:16:05,032 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/obj.pkl (recursive=False)
2025-04-06 01:16:05,032 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2025-04-06 01:16:05,033 - main.py[DEBUG]: no di_report found in config.
2025-04-06 01:16:05,035 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:05,036 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:05,039 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:05,039 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:05,042 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:05,042 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:05,046 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:05,046 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:05,060 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:05,060 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:05,065 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:05,065 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:05,079 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:05,080 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:05,086 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:05,086 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:05,096 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:05,097 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:05,109 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:05,110 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:05,120 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:05,120 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:05,126 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:05,126 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:05,130 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:05,130 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:05,139 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:05,140 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:05,144 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:05,144 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:05,149 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:05,149 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:05,152 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-04-06 01:16:05,153 - modules.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_migrator.py'>) with frequency always
2025-04-06 01:16:05,154 - handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
2025-04-06 01:16:05,154 - helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7fe6e6dfd550>)
2025-04-06 01:16:05,154 - cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
2025-04-06 01:16:05,154 - handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
2025-04-06 01:16:05,154 - modules.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2025-04-06 01:16:05,154 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2025-04-06 01:16:05,155 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_seed_random - wb: [644] 25 bytes
2025-04-06 01:16:05,165 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_seed_random (recursive=False)
2025-04-06 01:16:05,166 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_seed_random (recursive=False)
2025-04-06 01:16:05,167 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/i-0278353425af7a49b/sem/config_seed_random'>)
2025-04-06 01:16:05,167 - cc_seed_random.py[DEBUG]: no command provided
2025-04-06 01:16:05,167 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully
2025-04-06 01:16:05,167 - modules.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_bootcmd.py'>) with frequency always
2025-04-06 01:16:05,167 - handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
2025-04-06 01:16:05,167 - helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7fe6e6dfd550>)
2025-04-06 01:16:05,168 - cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
2025-04-06 01:16:05,168 - handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
2025-04-06 01:16:05,168 - modules.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_files.py'>) with frequency once-per-instance
2025-04-06 01:16:05,168 - handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
2025-04-06 01:16:05,169 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_write_files - wb: [644] 25 bytes
2025-04-06 01:16:05,170 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_write_files (recursive=False)
2025-04-06 01:16:05,171 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_write_files (recursive=False)
2025-04-06 01:16:05,172 - helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-0278353425af7a49b/sem/config_write_files'>)
2025-04-06 01:16:05,172 - cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
2025-04-06 01:16:05,172 - handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully
2025-04-06 01:16:05,172 - modules.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_metadata.py'>) with frequency once-per-instance
2025-04-06 01:16:05,173 - handlers.py[DEBUG]: start: init-network/config-write-metadata: running config-write-metadata with frequency once-per-instance
2025-04-06 01:16:05,173 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_write_metadata - wb: [644] 25 bytes
2025-04-06 01:16:05,175 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_write_metadata (recursive=False)
2025-04-06 01:16:05,176 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_write_metadata (recursive=False)
2025-04-06 01:16:05,177 - helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-0278353425af7a49b/sem/config_write_metadata'>)
2025-04-06 01:16:05,177 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsregion - wb: [644] 9 bytes
2025-04-06 01:16:05,182 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2025-04-06 01:16:05,183 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2025-04-06 01:16:05,184 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsregion to 0:0
2025-04-06 01:16:05,184 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsdomain - wb: [644] 13 bytes
2025-04-06 01:16:05,185 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2025-04-06 01:16:05,186 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2025-04-06 01:16:05,186 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsdomain to 0:0
2025-04-06 01:16:05,186 - handlers.py[DEBUG]: finish: init-network/config-write-metadata: SUCCESS: config-write-metadata ran successfully
2025-04-06 01:16:05,186 - modules.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2025-04-06 01:16:05,187 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2025-04-06 01:16:05,187 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7fe6e6dfd7f0>)
2025-04-06 01:16:05,187 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'mode': 'auto', 'devices': ['/'], 'ignore_growroot_disabled': False}
2025-04-06 01:16:05,187 - subp.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2025-04-06 01:16:05,213 - util.py[DEBUG]: Reading from /proc/1451/mountinfo (quiet=False)
2025-04-06 01:16:05,213 - util.py[DEBUG]: Read 2926 bytes from /proc/1451/mountinfo
2025-04-06 01:16:05,214 - util.py[DEBUG]: Reading from /sys/class/block/nvme0n1p1/partition (quiet=False)
2025-04-06 01:16:05,214 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/nvme0n1p1/partition
2025-04-06 01:16:05,216 - util.py[DEBUG]: Reading from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev (quiet=False)
2025-04-06 01:16:05,216 - util.py[DEBUG]: Read 6 bytes from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev
2025-04-06 01:16:05,217 - subp.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/nvme0n1', '1'] with allowed return codes [0] (shell=False, capture=True)
2025-04-06 01:16:05,350 - util.py[DEBUG]: resize_devices took 0.137 seconds
2025-04-06 01:16:05,350 - cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/nvme0n1, 1)
2025-04-06 01:16:05,352 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
2025-04-06 01:16:05,352 - modules.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2025-04-06 01:16:05,353 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2025-04-06 01:16:05,353 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7fe6e6dfd550>)
2025-04-06 01:16:05,353 - util.py[DEBUG]: Reading from /proc/1451/mountinfo (quiet=False)
2025-04-06 01:16:05,353 - util.py[DEBUG]: Read 2926 bytes from /proc/1451/mountinfo
2025-04-06 01:16:05,353 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/nvme0n1p1 mnt_point=/ path=/
2025-04-06 01:16:05,353 - cc_resizefs.py[DEBUG]: Resizing / (xfs) using xfs_growfs /
2025-04-06 01:16:05,355 - util.py[DEBUG]: Forked child 1589 who will run callback log_time
2025-04-06 01:16:05,355 - cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=xfs, val=noblock)
2025-04-06 01:16:05,356 - subp.py[DEBUG]: Running command ('xfs_growfs', '/') with allowed return codes [0] (shell=False, capture=True)
2025-04-06 01:16:05,356 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
2025-04-06 01:16:05,356 - modules.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_disk_setup' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disk_setup.py'>) with frequency once-per-instance
2025-04-06 01:16:05,357 - handlers.py[DEBUG]: start: init-network/config-disk_setup: running config-disk_setup with frequency once-per-instance
2025-04-06 01:16:05,357 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_disk_setup - wb: [644] 25 bytes
2025-04-06 01:16:05,359 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_disk_setup (recursive=False)
2025-04-06 01:16:05,396 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_disk_setup (recursive=False)
2025-04-06 01:16:05,396 - helpers.py[DEBUG]: Running config-disk_setup using lock (<FileLock using file '/var/lib/cloud/instances/i-0278353425af7a49b/sem/config_disk_setup'>)
2025-04-06 01:16:05,397 - handlers.py[DEBUG]: finish: init-network/config-disk_setup: SUCCESS: config-disk_setup ran successfully
2025-04-06 01:16:05,397 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2025-04-06 01:16:05,397 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2025-04-06 01:16:05,397 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_mounts - wb: [644] 25 bytes
2025-04-06 01:16:05,410 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_mounts (recursive=False)
2025-04-06 01:16:05,411 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_mounts (recursive=False)
2025-04-06 01:16:05,412 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-0278353425af7a49b/sem/config_mounts'>)
2025-04-06 01:16:05,412 - cc_mounts.py[DEBUG]: mounts configuration is []
2025-04-06 01:16:05,413 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2025-04-06 01:16:05,413 - util.py[DEBUG]: Read 217 bytes from /etc/fstab
2025-04-06 01:16:05,413 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2025-04-06 01:16:05,413 - DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
2025-04-06 01:16:05,413 - cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
2025-04-06 01:16:05,413 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2025-04-06 01:16:05,413 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2025-04-06 01:16:05,413 - DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
2025-04-06 01:16:05,413 - cc_mounts.py[DEBUG]: changed default device swap => None
2025-04-06 01:16:05,413 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2025-04-06 01:16:05,413 - cc_mounts.py[DEBUG]: no need to setup swap
2025-04-06 01:16:05,413 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2025-04-06 01:16:05,413 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully
2025-04-06 01:16:05,413 - modules.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_hostname.py'>) with frequency always
2025-04-06 01:16:05,414 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency always
2025-04-06 01:16:05,414 - helpers.py[DEBUG]: Running config-set_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7fe6e6dfd7f0>)
2025-04-06 01:16:05,414 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2025-04-06 01:16:05,414 - util.py[DEBUG]: Read 78 bytes from /var/lib/cloud/data/set-hostname
2025-04-06 01:16:05,414 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2025-04-06 01:16:05,414 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully
2025-04-06 01:16:05,414 - modules.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2025-04-06 01:16:05,415 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2025-04-06 01:16:05,415 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7fe6e6dfd8b0>)
2025-04-06 01:16:05,415 - cc_update_hostname.py[DEBUG]: Updating hostname to ip-172-31-27-108.ec2.internal (ip-172-31-27-108)
2025-04-06 01:16:05,415 - subp.py[DEBUG]: Running command ['hostname'] with allowed return codes [0] (shell=False, capture=True)
2025-04-06 01:16:05,425 - util.py[DEBUG]: backgrounded Resizing took 0.069 seconds
2025-04-06 01:16:05,428 - __init__.py[DEBUG]: Attempting to update hostname to ip-172-31-27-108.ec2.internal in 1 files
2025-04-06 01:16:05,429 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 29 bytes
2025-04-06 01:16:05,430 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2025-04-06 01:16:05,432 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2025-04-06 01:16:05,433 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully
2025-04-06 01:16:05,433 - modules.py[DEBUG]: Running module update_etc_hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_etc_hosts.py'>) with frequency always
2025-04-06 01:16:05,434 - handlers.py[DEBUG]: start: init-network/config-update_etc_hosts: running config-update_etc_hosts with frequency always
2025-04-06 01:16:05,434 - helpers.py[DEBUG]: Running config-update_etc_hosts using lock (<cloudinit.helpers.DummyLock object at 0x7fe6e6dfd7f0>)
2025-04-06 01:16:05,434 - cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update_etc_hosts
2025-04-06 01:16:05,434 - handlers.py[DEBUG]: finish: init-network/config-update_etc_hosts: SUCCESS: config-update_etc_hosts ran successfully
2025-04-06 01:16:05,434 - modules.py[DEBUG]: Running module ca-certs (<module 'cloudinit.config.cc_ca_certs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ca_certs.py'>) with frequency once-per-instance
2025-04-06 01:16:05,434 - handlers.py[DEBUG]: start: init-network/config-ca-certs: running config-ca-certs with frequency once-per-instance
2025-04-06 01:16:05,434 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_ca_certs - wb: [644] 24 bytes
2025-04-06 01:16:05,435 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_ca_certs (recursive=False)
2025-04-06 01:16:05,437 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_ca_certs (recursive=False)
2025-04-06 01:16:05,437 - helpers.py[DEBUG]: Running config-ca-certs using lock (<FileLock using file '/var/lib/cloud/instances/i-0278353425af7a49b/sem/config_ca_certs'>)
2025-04-06 01:16:05,437 - cc_ca_certs.py[DEBUG]: Skipping module named ca-certs, no 'ca_certs' key in configuration
2025-04-06 01:16:05,437 - handlers.py[DEBUG]: finish: init-network/config-ca-certs: SUCCESS: config-ca-certs ran successfully
2025-04-06 01:16:05,438 - modules.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_rsyslog.py'>) with frequency once-per-instance
2025-04-06 01:16:05,438 - handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
2025-04-06 01:16:05,438 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_rsyslog - wb: [644] 24 bytes
2025-04-06 01:16:05,450 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_rsyslog (recursive=False)
2025-04-06 01:16:05,452 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_rsyslog (recursive=False)
2025-04-06 01:16:05,452 - helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-0278353425af7a49b/sem/config_rsyslog'>)
2025-04-06 01:16:05,453 - cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
2025-04-06 01:16:05,453 - handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully
2025-04-06 01:16:05,453 - modules.py[DEBUG]: Running module selinux (<module 'cloudinit.config.cc_selinux' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_selinux.py'>) with frequency once-per-instance
2025-04-06 01:16:05,453 - handlers.py[DEBUG]: start: init-network/config-selinux: running config-selinux with frequency once-per-instance
2025-04-06 01:16:05,453 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_selinux - wb: [644] 25 bytes
2025-04-06 01:16:05,454 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_selinux (recursive=False)
2025-04-06 01:16:05,455 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_selinux (recursive=False)
2025-04-06 01:16:05,456 - helpers.py[DEBUG]: Running config-selinux using lock (<FileLock using file '/var/lib/cloud/instances/i-0278353425af7a49b/sem/config_selinux'>)
2025-04-06 01:16:05,472 - cc_selinux.py[DEBUG]: Current SELinux state is enabled
2025-04-06 01:16:05,473 - cc_selinux.py[DEBUG]: Current SELinux mode is permissive
2025-04-06 01:16:05,473 - cc_selinux.py[DEBUG]: Configured SELinux mode is permissive
2025-04-06 01:16:05,473 - cc_selinux.py[DEBUG]: Current SELinux policy is targeted
2025-04-06 01:16:05,473 - cc_selinux.py[DEBUG]: No SELinux configuration, skipping
2025-04-06 01:16:05,473 - handlers.py[DEBUG]: finish: init-network/config-selinux: SUCCESS: config-selinux ran successfully
2025-04-06 01:16:05,473 - modules.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2025-04-06 01:16:05,474 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
2025-04-06 01:16:05,474 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_users_groups - wb: [644] 25 bytes
2025-04-06 01:16:05,475 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_users_groups (recursive=False)
2025-04-06 01:16:05,478 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_users_groups (recursive=False)
2025-04-06 01:16:05,479 - helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-0278353425af7a49b/sem/config_users_groups'>)
2025-04-06 01:16:05,490 - __init__.py[INFO]: User ec2-user already exists, skipping.
2025-04-06 01:16:05,490 - subp.py[DEBUG]: Running command ['passwd', '-l', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
2025-04-06 01:16:05,572 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
2025-04-06 01:16:05,583 - util.py[DEBUG]: Read 4375 bytes from /etc/sudoers
2025-04-06 01:16:05,586 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d (recursive=False)
2025-04-06 01:16:05,587 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - ab: [None] 59 bytes
2025-04-06 01:16:05,590 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d/90-cloud-init-users (recursive=False)
2025-04-06 01:16:05,591 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
2025-04-06 01:16:05,591 - modules.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2025-04-06 01:16:05,591 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2025-04-06 01:16:05,591 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_ssh - wb: [644] 25 bytes
2025-04-06 01:16:05,594 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_ssh (recursive=False)
2025-04-06 01:16:05,596 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_ssh (recursive=False)
2025-04-06 01:16:05,597 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-0278353425af7a49b/sem/config_ssh'>)
2025-04-06 01:16:05,598 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2025-04-06 01:16:05,626 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2025-04-06 01:16:05,650 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2025-04-06 01:16:05,672 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2025-04-06 01:16:05,692 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ed25519_key.pub (quiet=False)
2025-04-06 01:16:05,692 - util.py[DEBUG]: Read 116 bytes from /etc/ssh/ssh_host_ed25519_key.pub
2025-04-06 01:16:05,692 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ecdsa_key.pub (quiet=False)
2025-04-06 01:16:05,692 - util.py[DEBUG]: Read 196 bytes from /etc/ssh/ssh_host_ecdsa_key.pub
2025-04-06 01:16:05,694 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-04-06 01:16:05,699 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2025-04-06 01:16:05,700 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh to 1000:1000
2025-04-06 01:16:05,702 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=False)
2025-04-06 01:16:05,702 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2025-04-06 01:16:05,703 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-04-06 01:16:05,703 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-04-06 01:16:05,703 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 1000:1000
2025-04-06 01:16:05,703 - util.py[DEBUG]: Reading from /home/ec2-user/.ssh/authorized_keys (quiet=False)
2025-04-06 01:16:05,704 - util.py[DEBUG]: Read 0 bytes from /home/ec2-user/.ssh/authorized_keys
2025-04-06 01:16:05,704 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2025-04-06 01:16:05,704 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-04-06 01:16:05,704 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-04-06 01:16:05,704 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=True)
2025-04-06 01:16:05,707 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-04-06 01:16:05,707 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2025-04-06 01:16:05,707 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2025-04-06 01:16:05,709 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2025-04-06 01:16:05,720 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-04-06 01:16:05,720 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-04-06 01:16:05,720 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2025-04-06 01:16:05,721 - util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
2025-04-06 01:16:05,721 - util.py[DEBUG]: Read 0 bytes from /root/.ssh/authorized_keys
2025-04-06 01:16:05,721 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2025-04-06 01:16:05,721 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-04-06 01:16:05,721 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-04-06 01:16:05,722 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2025-04-06 01:16:05,723 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
2025-04-06 01:16:05,724 - main.py[DEBUG]: Ran 17 modules with 0 failures
2025-04-06 01:16:05,724 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpc33fcrbm) - w: [644] 486 bytes/chars
2025-04-06 01:16:05,724 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-04-06 01:16:05,725 - util.py[DEBUG]: Read 11 bytes from /proc/uptime
2025-04-06 01:16:05,725 - util.py[DEBUG]: cloud-init mode 'init' took 2.298 seconds (2.30)
2025-04-06 01:16:05,725 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2025-04-06 01:16:06,874 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:config' at Sun, 06 Apr 2025 01:16:06 +0000. Up 11.39 seconds.
2025-04-06 01:16:06,884 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:06,885 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:06,900 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:06,900 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:06,903 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:06,904 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:06,909 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:06,910 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:06,920 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:06,920 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:06,923 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:06,923 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:06,930 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:06,930 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:06,935 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:06,935 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:06,949 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:06,950 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:06,953 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:06,953 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:06,956 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-04-06 01:16:06,956 - modules.py[INFO]: Skipping modules 'ssh-import-id' because they are not verified on distro 'amazon'.  To run anyway, add them to 'unverified_modules' in config.
2025-04-06 01:16:06,957 - modules.py[DEBUG]: Running module keyboard (<module 'cloudinit.config.cc_keyboard' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_keyboard.py'>) with frequency once-per-instance
2025-04-06 01:16:06,957 - handlers.py[DEBUG]: start: modules-config/config-keyboard: running config-keyboard with frequency once-per-instance
2025-04-06 01:16:06,957 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_keyboard - wb: [644] 24 bytes
2025-04-06 01:16:06,970 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_keyboard (recursive=False)
2025-04-06 01:16:06,974 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_keyboard (recursive=False)
2025-04-06 01:16:06,974 - helpers.py[DEBUG]: Running config-keyboard using lock (<FileLock using file '/var/lib/cloud/instances/i-0278353425af7a49b/sem/config_keyboard'>)
2025-04-06 01:16:06,974 - cc_keyboard.py[DEBUG]: Skipping module named keyboard, no 'keyboard' section found
2025-04-06 01:16:06,975 - handlers.py[DEBUG]: finish: modules-config/config-keyboard: SUCCESS: config-keyboard ran successfully
2025-04-06 01:16:06,975 - modules.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2025-04-06 01:16:06,975 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2025-04-06 01:16:06,975 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_locale - wb: [644] 25 bytes
2025-04-06 01:16:06,976 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_locale (recursive=False)
2025-04-06 01:16:06,977 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_locale (recursive=False)
2025-04-06 01:16:06,978 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-0278353425af7a49b/sem/config_locale'>)
2025-04-06 01:16:06,978 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2025-04-06 01:16:06,978 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2025-04-06 01:16:06,978 - cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
2025-04-06 01:16:06,978 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2025-04-06 01:16:06,978 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2025-04-06 01:16:06,979 - util.py[DEBUG]: Writing to /etc/locale.conf - wb: [644] 17 bytes
2025-04-06 01:16:06,982 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2025-04-06 01:16:06,985 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2025-04-06 01:16:06,985 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
2025-04-06 01:16:06,986 - modules.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2025-04-06 01:16:06,986 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
2025-04-06 01:16:06,986 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_set_passwords - wb: [644] 25 bytes
2025-04-06 01:16:07,000 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_set_passwords (recursive=False)
2025-04-06 01:16:07,001 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_set_passwords (recursive=False)
2025-04-06 01:16:07,002 - helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-0278353425af7a49b/sem/config_set_passwords'>)
2025-04-06 01:16:07,002 - subp.py[DEBUG]: Running command ['systemctl', 'status', 'sshd'] with allowed return codes [0] (shell=False, capture=True)
2025-04-06 01:16:07,044 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-04-06 01:16:07,044 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2025-04-06 01:16:07,044 - ssh_util.py[DEBUG]: line 65: option PasswordAuthentication already set to no
2025-04-06 01:16:07,044 - cc_set_passwords.py[DEBUG]: No need to restart SSH service, PasswordAuthentication not updated.
2025-04-06 01:16:07,045 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
2025-04-06 01:16:07,045 - modules.py[DEBUG]: Running module yum-variables (<module 'cloudinit.config.cc_yum_variables' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_variables.py'>) with frequency once-per-instance
2025-04-06 01:16:07,045 - handlers.py[DEBUG]: start: modules-config/config-yum-variables: running config-yum-variables with frequency once-per-instance
2025-04-06 01:16:07,045 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_yum_variables - wb: [644] 25 bytes
2025-04-06 01:16:07,046 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_yum_variables (recursive=False)
2025-04-06 01:16:07,048 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_yum_variables (recursive=False)
2025-04-06 01:16:07,049 - helpers.py[DEBUG]: Running config-yum-variables using lock (<FileLock using file '/var/lib/cloud/instances/i-0278353425af7a49b/sem/config_yum_variables'>)
2025-04-06 01:16:07,049 - cc_yum_variables.py[INFO]: handling yum-variables
2025-04-06 01:16:07,049 - cc_yum_variables.py[INFO]: cfg = {'cloud_final_modules': [['scripts-user', 'always']], 'repo_releasever': 2023.6, 'repo_upgrade': 'none', 'power_state': {'delay': 'now', 'mode': 'reboot', 'message': 'Rebooting machine to apply SELinux kernel commandline setting', 'condition': 'test -f /run/cloud-init-selinux-reboot'}, 'write_metadata': [{'path': '/etc/dnf/vars/awsregion', 'data': [{'identity': 'region'}, 'default']}, {'path': '/etc/dnf/vars/awsdomain', 'data': [{'metadata': 'services/domain'}, 'amazonaws.com']}], '_log': ['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n", '[handler_cloudLogHandler]\nclass=handlers.SysLogHandler\nlevel=DEBUG\nformatter=simpleFormatter\nargs=("/dev/log", handlers.SysLogHandler.LOG_USER)\n'], 'log_cfgs': [['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n"]], 'output': {'all': '| tee -a /var/log/cloud-init-output.log'}, 'network': {'config': 'disabled'}, 'datasource_list': ['Ec2', 'None'], 'datasource': {'Ec2': {'metadata_urls': ['http://169.254.169.254:80', 'http://[fd00:ec2::254]:80'], 'apply_full_imds_network_config': False}}, 'ssh_genkeytypes': ['ed25519', 'ecdsa'], 'users': ['default'], 'disable_root': True, 'mount_default_fields': [None, None, 'auto', 'defaults,nofail', '0', '2'], 'resize_rootfs': 'noblock', 'resize_rootfs_tmp': '/dev', 'ssh_pwauth': False, 'preserve_hostname': False, 'cloud_init_modules': ['migrator', 'seed_random', 'bootcmd', 'write-files', 'write-metadata', 'growpart', 'resizefs', 'disk_setup', 'mounts', 'set_hostname', 'update_hostname', 'update_etc_hosts', 'ca-certs', 'rsyslog', 'selinux', 'users-groups', 'ssh'], 'cloud_config_modules': ['ssh-import-id', 'keyboard', 'locale', 'set-passwords', 'yum-variables', 'yum-add-repo', 'ntp', 'timezone', 'disable-ec2-metadata', 'runcmd'], 'def_log_file': '/var/log/cloud-init.log', 'syslog_fix_perms': ['syslog:adm', 'root:adm', 'root:wheel', 'root:root'], 'vendor_data': {'enabled': True, 'prefix': []}, 'vendor_data2': {'enabled': True, 'prefix': []}}
2025-04-06 01:16:07,049 - cc_yum_variables.py[INFO]: No yum vars to delete
2025-04-06 01:16:07,049 - cc_yum_variables.py[INFO]: No yum vars to set
2025-04-06 01:16:07,049 - handlers.py[DEBUG]: finish: modules-config/config-yum-variables: SUCCESS: config-yum-variables ran successfully
2025-04-06 01:16:07,049 - modules.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_add_repo.py'>) with frequency once-per-instance
2025-04-06 01:16:07,059 - handlers.py[DEBUG]: start: modules-config/config-yum-add-repo: running config-yum-add-repo with frequency once-per-instance
2025-04-06 01:16:07,060 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_yum_add_repo - wb: [644] 24 bytes
2025-04-06 01:16:07,061 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_yum_add_repo (recursive=False)
2025-04-06 01:16:07,062 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_yum_add_repo (recursive=False)
2025-04-06 01:16:07,062 - helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-0278353425af7a49b/sem/config_yum_add_repo'>)
2025-04-06 01:16:07,062 - cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
2025-04-06 01:16:07,063 - handlers.py[DEBUG]: finish: modules-config/config-yum-add-repo: SUCCESS: config-yum-add-repo ran successfully
2025-04-06 01:16:07,063 - modules.py[DEBUG]: Running module ntp (<module 'cloudinit.config.cc_ntp' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ntp.py'>) with frequency once-per-instance
2025-04-06 01:16:07,063 - handlers.py[DEBUG]: start: modules-config/config-ntp: running config-ntp with frequency once-per-instance
2025-04-06 01:16:07,063 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_ntp - wb: [644] 25 bytes
2025-04-06 01:16:07,064 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_ntp (recursive=False)
2025-04-06 01:16:07,065 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_ntp (recursive=False)
2025-04-06 01:16:07,066 - helpers.py[DEBUG]: Running config-ntp using lock (<FileLock using file '/var/lib/cloud/instances/i-0278353425af7a49b/sem/config_ntp'>)
2025-04-06 01:16:07,066 - cc_ntp.py[DEBUG]: Skipping module named ntp, not present or disabled by cfg
2025-04-06 01:16:07,066 - handlers.py[DEBUG]: finish: modules-config/config-ntp: SUCCESS: config-ntp ran successfully
2025-04-06 01:16:07,066 - modules.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_timezone.py'>) with frequency once-per-instance
2025-04-06 01:16:07,066 - handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
2025-04-06 01:16:07,066 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_timezone - wb: [644] 24 bytes
2025-04-06 01:16:07,067 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_timezone (recursive=False)
2025-04-06 01:16:07,068 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_timezone (recursive=False)
2025-04-06 01:16:07,069 - helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-0278353425af7a49b/sem/config_timezone'>)
2025-04-06 01:16:07,069 - cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
2025-04-06 01:16:07,069 - handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully
2025-04-06 01:16:07,069 - modules.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disable_ec2_metadata.py'>) with frequency always
2025-04-06 01:16:07,079 - handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
2025-04-06 01:16:07,079 - helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7fb00694e2b0>)
2025-04-06 01:16:07,080 - cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
2025-04-06 01:16:07,080 - handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
2025-04-06 01:16:07,080 - modules.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_runcmd.py'>) with frequency once-per-instance
2025-04-06 01:16:07,080 - handlers.py[DEBUG]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
2025-04-06 01:16:07,080 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_runcmd - wb: [644] 25 bytes
2025-04-06 01:16:07,081 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_runcmd (recursive=False)
2025-04-06 01:16:07,082 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0278353425af7a49b/sem/config_runcmd (recursive=False)
2025-04-06 01:16:07,083 - helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-0278353425af7a49b/sem/config_runcmd'>)
2025-04-06 01:16:07,083 - cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
2025-04-06 01:16:07,083 - handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd ran successfully
2025-04-06 01:16:07,083 - main.py[DEBUG]: Ran 9 modules with 0 failures
2025-04-06 01:16:07,084 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpw7yn5tw4) - w: [644] 514 bytes/chars
2025-04-06 01:16:07,084 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-04-06 01:16:07,084 - util.py[DEBUG]: Read 11 bytes from /proc/uptime
2025-04-06 01:16:07,084 - util.py[DEBUG]: cloud-init mode 'modules' took 0.451 seconds (0.45)
2025-04-06 01:16:07,084 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2025-04-06 01:16:07,982 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:final' at Sun, 06 Apr 2025 01:16:07 +0000. Up 12.50 seconds.
2025-04-06 01:16:07,991 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-04-06 01:16:07,992 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-04-06 01:16:07,994 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-04-06 01:16:08,000 - modules.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_scripts_user.py'>) with frequency always
2025-04-06 01:16:08,000 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency always
2025-04-06 01:16:08,000 - helpers.py[DEBUG]: Running config-scripts-user using lock (<cloudinit.helpers.DummyLock object at 0x7f8fb9933e50>)
2025-04-06 01:16:08,001 - subp.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/user-data.txt'] with allowed return codes [0] (shell=False, capture=False)
2025-04-06 01:17:11,643 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
2025-04-06 01:17:11,647 - main.py[DEBUG]: Ran 1 modules with 0 failures
2025-04-06 01:17:11,648 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp_fjxl0n6) - w: [644] 541 bytes/chars
2025-04-06 01:17:11,650 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmp_zyjl2_m) - w: [644] 64 bytes/chars
2025-04-06 01:17:11,650 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2025-04-06 01:17:11,651 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-04-06 01:17:11,651 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
2025-04-06 01:17:11,651 - util.py[DEBUG]: cloud-init mode 'modules' took 63.889 seconds (62.51)
2025-04-06 01:17:11,651 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
